### ISSUE TITLE
About  Visualization of the Lane Graph 

### ISSUE THREAD

**Issue by gilgamsh** [nachiket92/PGP#11]
Hi, thank you so much for your great work and open source.
I'm interested in the visualization of the lane graph. Could you please give some tutorial about that?

**Comment by nachiket92** [comment]
You could use this function to visualize the lane graph and the ground truth visited nodes:
https://github.com/nachiket92/PGP/blob/9c98885a845cacf3f73277a8e8c1e5f5fe03467c/datasets/nuScenes/nuScenes_graphs.py#L413-L463
