### ISSUE TITLE
Error when trying to preprocess data

### ISSUE THREAD

**Issue by anubhavjetley2424** [nachiket92/PGP#30]
This error occurs in the multiprocessing library saying 'AttributeError: module 'multiprocessing.reduction' has no attribute 'dump'
. Anyone know why this keeps happening

![image](https://github.com/nachiket92/PGP/assets/88648167/03c6f858-90d5-4ddc-9070-983bab22d190)

**Comment by KYYOnull** [comment]
i have the same problem
